### ISSUE TITLE
headless daemon can't restart after stopping

### ISSUE THREAD

**Issue by ghost** [KIZUNACOIN/kizunacoin-headless#1]
```
/home/kizuna/kizunacoin-headless/node_modules/core/network.js:743
					throw Error("known bad "+unit+": "+error);
					^

Error: known bad ET2dbWJU6jP4D6ALMXJxsaVGg0biG9hV2dhEOVaPFyE=: src output must be before last ball
    at Object.ifKnownBad (/home/kizuna/kizunacoin-headless/node_modules/core/network.js:743:12)
    at /home/kizuna/kizunacoin-headless/node_modules/core/joint_storage.js:28:61
    at /home/kizuna/kizunacoin-headless/node_modules/core/sqlite_pool.js:222:5
    at Statement.<anonymous> (/home/kizuna/kizunacoin-headless/node_modules/core/sqlite_pool.js:115:6)
```

**Comment by KIZUNACOIN** [comment]
Please check again.
It was unstable unit limit issue.
Resolved.

**Comment by KIZUNACOIN** [comment]
Done
